#LOCAL profile configuration
#  datasource:
#      url: jdbc:postgresql://localhost:5432/postgres
#      username: postgres
#      password: 123123
#      driver-class-name: org.postgresql.Driver
spring:
  data:
    mongodb:
      uri:  mongodb://127.0.0.1:27017/trade